### PR TITLE
[WIP] Version 0.1.0

### PR DESCRIPTION
**Pull request by sealmove**
This PR was migrated from [another one](https://github.com/fermyon/spin/pull/716) in the [main spin repository](https://github.com/fermyon/spin).

Signed-off-by: sealmove <sealmove@proton.me>

### CODE REVIEW

**Comment by radu-matei** [comment]
@sealmove — This is awesome, thank you SO much for your work here!
Is this PR still a WIP?

**Comment by sealmove** [comment]
Hey @radu-matei. This could be merged, but I have been working on outbound http which is not completed yet. I haven't worked on the SDK the last couple of weeks but I am coming back to it very soon.

**Comment by radu-matei** [comment]
Outbound HTTP can definitely be a separate PR.
One thing that would be very useful for this PR is a readme describing how to use the project.

**Review by radu-matei — APPROVED** [review]
Thanks, this looks great for a first pass!

LGTM

**Pull request merged**
